### ISSUE TITLE
[RFC] Add support for vehicle positions

### ISSUE THREAD

**Issue by cedarbaum** [jamespfennell/gtfs#3]
I recently started looking into adding vehicle positions to Transiter, and it seems for that this package also needs to be updated to fully parse the `Vehicle` real time entity type. My first thought was to modify the existing `gtfs.Vehicle` type to something like this:

```go
type VehiclePosition = gtfsrt.VehiclePosition

type Vehicle struct {
	ID *VehicleID

	Trip *Trip

	Position *VehiclePosition

	IsEntityInMessage bool
}
```

This adds some redundancies to the existing structure, since `VehicleID` already contains some information in `VehiclePosition`. If backwards compatibility isn't a concern, then the structure could be further modified to match `gtfsrt.VehiclePosition`.

After the data contract is settled, I _think_ this should be a relatively simple change (famous last words haha) but I wanted to get your initial impressions on the above data structure change as well as any other thoughts you may have on the larger idea of implementing vehicles positions end-to-end.

**Comment by jamespfennell** [comment]
Adding support for vehicles here and in Transiter sounds awesome!

My original thinking for this package was that the `Vehicle` struct would actually correspond to the `VehiclePosition` GTFS proto message directly. So instead of adding a position field to `Vehicle`, the fields in `VehiclePosition` would be added directly to `Vehicle`. This is similar to how trips behave in this package. The trips data is transmitted in a GTFS proto message called `TripUpdate`, but the GTFS parser converts this into a struct called `Trip`.

The motivation was my feeling that "TripUpdate" and "VehiclePosition" are kind of bad names. The data in "VehiclePosition" usually isn't just the position - it's a complete description of a vehicle and its current state. Similar with trip updates, which fully describe a trip. (FWIW, I get why these names were chosen - the GTFS realtime spec was originally thought of as providing auxiliary data on top of GTFS static data, so referring things as "updates" makes sense). I thought it was simpler to rename them.

On the other hand, renaming things makes things harder to follow.

So, my suggestion would be to optionally rename `Vehicle` to `VehiclePosition`, and then add the GTFS fields directly there. So something like:

```
type Vehicle struct {
	// existing fields
	ID *VehicleID
	Trip *Trip
	IsEntityInMessage bool

	// new fields
	Position *Position
	CurrentStopSequence *int64
	StopID *string
	// etc...
}
```

What do you think?

Also, yeah I wouldn't worry about backwards compatibility.... :)

**Comment by jamespfennell** [comment]
I think I would prefer to keep the name vehicle, but totally open to renaming too. Transiter already has a vehicle table actually, it's just unused...

**Comment by cedarbaum** [comment]
Appreciate the initial feedback! I'll have a PR soon with a first pass at this.

**Comment by jamespfennell** [comment]
FYI just made a new release v0.1.14 that includes the PR.

**Comment by cedarbaum** [comment]
Awesome, thanks! I'll close this issue and start looking into the Transiter changes next.
